# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  workflow_call:
   inputs:
     java-version: 
       required: false
       type: string
       default: '17'
permissions:
 contents: read
 packages: write
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name : Checkout code 
        uses: actions/checkout@v4
        with:
          java-version: ${{inputs.java-version}}
          distribution: 'temurin'

      - name: Build with maven
        run: mvn clean package -DskipTests
        
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Vérifier l'installation de Docker Compose


      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set repo name to lowercase
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          
      - name: Build and push Docker image with Docker Compose
        run: |
          docker-compose build
          docker-compose push
      - name: Cleanup
        run: docker system prune -f
