name: Smoke Test

on:
  workflow_call:
    secrets:
      SERVER_HOST:
        required: true

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for services to start
        run: sleep 30

      - name: Check Eureka
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            http://${{ secrets.SERVER_HOST }}:8761/actuator/health)
          [ "$STATUS" = "200" ] || (echo "Eureka KO ($STATUS)" && exit 1)

      - name: Check Config Server
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            http://${{ secrets.SERVER_HOST }}:8888/actuator/health)
          [ "$STATUS" = "200" ] || (echo "Config Server KO ($STATUS)" && exit 1)

     
      - name: Check Billing Service
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            http://${{ secrets.SERVER_HOST }}:8081/actuator/health)
          [ "$STATUS" = "200" ] || (echo "Billing KO ($STATUS)" && exit 1)

      - name: Check Frontend via Nginx
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            http://${{ secrets.SERVER_HOST }})
          [ "$STATUS" = "200" ] || (echo "Frontend KO ($STATUS)" && exit 1)
