name: CI-CD Orchestrator

on:
 push:
   branches: [ main ]

jobs:
  sast:
    uses: org/Devops-workflow/.github/workflows/sast.yml@v1

  build:
    needs: sast
    uses:  org/Devops-workflow/.github/workflows/build.yml@v1

  deloyment:
    needs: build
    uses:  KrakennTunisie/Devops-workflow/.github/workflows/deployment.yml@v1
