name: CI-CD Orchestrator

on:
 push:
   branches: [ main ]

jobs:
  sast:
    uses: org/Devops-workflow/.github/workflows/SAST.yml@v1

  buildAPP:
    needs: sast
    uses:  org/Devops-workflow/.github/workflows/build.yml@v1

  deloyment:
    needs: buildAPP
    uses:  org/Devops-workflow/.github/workflows/deployment.yml@v1
