name: CI-CD Orchestrator

on:
 workflow_call:
   inputs:
     java-version:
        required: false
        type: string
        default: "17"
   secrets:
       SERVER_HOST:
         required: true
       SERVER_USER:
         required: true
       SERVER_PASSWORD: 
         required: true
       EUREKA_PORT: 
        required: true
       
    
jobs:
  sast:
    uses: KrakennTunisie/Devops_workflow/.github/workflows/SAST.yml@main
    secrets: inherit

  tests:
    needs: sast
    uses: KrakennTunisie/Devops_workflow/.github/workflows/test.yml@main
    secrets: inherit
    with:
      java-version: "17"
      maven-args: "-B -ntp verify"
      working-directory: "."    

  build:
    needs: tests
    uses:  KrakennTunisie/Devops_workflow/.github/workflows/build.yml@main

  deployment:
    needs: build
    uses:  KrakennTunisie/Devops_workflow/.github/workflows/deployment.yml@main
    secrets:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      EUREKA_PORT: ${{ secrets.EUREKA_PORT }}
    with:
      service-name: ${{ github.event.repository.name }}
